import { Task, Contractor } from "./types";
import { addDays, todayISO } from "./dateUtils";

export function getSeedTasks(): Task[] {
  const today = todayISO();
  return [
    {
      id: crypto.randomUUID(),
      room: "Kitchen",
      appliance: "Dishwasher",
      taskType: "Cleaning",
      lastDoneDate: addDays(today, -120),
      recurrenceInterval: 90,
      recurrenceLabel: "Quarterly",
      nextDueDate: addDays(today, -30),
      isOneTime: false,
      status: "overdue",
      completedDate: null,
      contractorName: "",
      contractorPhone: "",
      contractorNote: "",
      cost: 45,
      costHistory: [{ date: addDays(today, -120), cost: 45, note: "Deep cleaned filters" }],
    },
    {
      id: crypto.randomUUID(),
      room: "Exterior",
      appliance: "Roof Gutters",
      taskType: "Cleaning",
      lastDoneDate: addDays(today, -200),
      recurrenceInterval: 180,
      recurrenceLabel: "Bi-Annually",
      nextDueDate: addDays(today, -20),
      isOneTime: false,
      status: "overdue",
      completedDate: null,
      contractorName: "Mike's Gutters",
      contractorPhone: "555-0102",
      contractorNote: "Great work last time",
      cost: 150,
      costHistory: [{ date: addDays(today, -200), cost: 150, note: "Full gutter cleanout" }],
    },
    {
      id: crypto.randomUUID(),
      room: "Living Room",
      appliance: "HVAC Filter",
      taskType: "Replacement",
      lastDoneDate: addDays(today, -25),
      recurrenceInterval: 30,
      recurrenceLabel: "Monthly",
      nextDueDate: addDays(today, 5),
      isOneTime: false,
      status: "pending",
      completedDate: null,
      contractorName: "",
      contractorPhone: "",
      contractorNote: "",
      cost: 25,
      costHistory: [{ date: addDays(today, -25), cost: 25, note: "MERV 13 filter" }],
    },
    {
      id: crypto.randomUUID(),
      room: "Bathroom",
      appliance: "Water Heater",
      taskType: "Inspection",
      lastDoneDate: addDays(today, -300),
      recurrenceInterval: 365,
      recurrenceLabel: "Yearly",
      nextDueDate: addDays(today, 65),
      isOneTime: false,
      status: "pending",
      completedDate: null,
      contractorName: "Joe's Plumbing",
      contractorPhone: "555-0199",
      contractorNote: "",
      cost: 120,
      costHistory: [{ date: addDays(today, -300), cost: 120, note: "Annual flush and inspect" }],
    },
    {
      id: crypto.randomUUID(),
      room: "Garage",
      appliance: "Garage Door Springs",
      taskType: "Servicing",
      lastDoneDate: addDays(today, -60),
      recurrenceInterval: 180,
      recurrenceLabel: "Bi-Annually",
      nextDueDate: addDays(today, 120),
      isOneTime: false,
      status: "pending",
      completedDate: null,
      contractorName: "",
      contractorPhone: "",
      contractorNote: "",
      cost: 85,
      costHistory: [{ date: addDays(today, -60), cost: 85, note: "Lubricated and adjusted" }],
    },
    {
      id: crypto.randomUUID(),
      room: "Bedroom",
      appliance: "Smoke Detector Battery",
      taskType: "Replacement",
      lastDoneDate: addDays(today, -10),
      recurrenceInterval: 365,
      recurrenceLabel: "Yearly",
      nextDueDate: addDays(today, 355),
      isOneTime: false,
      status: "pending",
      completedDate: null,
      contractorName: "",
      contractorPhone: "",
      contractorNote: "",
      cost: 12,
      costHistory: [{ date: addDays(today, -10), cost: 12, note: "Replaced 9V batteries" }],
    },
  ];
}

export function getSeedContractors(): Contractor[] {
  return [
    {
      id: crypto.randomUUID(),
      name: "Joe's Plumbing",
      phone: "555-0199",
      email: "joe@plumbing.com",
      specialty: "Plumbing",
      rating: 4,
      notes: "Reliable, fair pricing",
    },
    {
      id: crypto.randomUUID(),
      name: "Mike's Gutters",
      phone: "555-0102",
      email: "mike@gutterclean.com",
      specialty: "General",
      rating: 5,
      notes: "Excellent gutter and exterior work",
    },
  ];
}
